//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İs_Takip_Projesi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GorevDetaylar
    {
        public int ID { get; set; }
        public Nullable<int> Görev { get; set; }
        public string Açıklama { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Saat { get; set; }
    
        public virtual Gorevler Gorevler { get; set; }
    }
}
