//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İs_Takip_Projesi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gorevler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gorevler()
        {
            this.GorevDetaylar = new HashSet<GorevDetaylar>();
        }
    
        public int ID { get; set; }
        public Nullable<int> GörevVeren { get; set; }
        public Nullable<int> GörevAlan { get; set; }
        public string Açıklama { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GorevDetaylar> GorevDetaylar { get; set; }
        public virtual Personel Personel { get; set; }
        public virtual Personel Personel1 { get; set; }
    }
}
